version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    entrypoint: ["sh", "/app/entrypoint.sh"]  # ใช้ entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - MYSQL_DATABASE=dbthewinner
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_HOST=db
      - MYSQL_PORT=3306


  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dbthewinner
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - db

volumes:
  mysql_data:
