# Generated by Django 5.1.3 on 2025-02-21 02:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HireforAdmin',
            fields=[
                ('HireA_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Width', models.FloatField(verbose_name='Width (m.)')),
                ('Length', models.FloatField(verbose_name='Length (m.)')),
                ('Height', models.FloatField(verbose_name='Height (m.)')),
                ('Type', models.CharField(max_length=100)),
                ('Budget', models.CharField(max_length=150)),
                ('Location', models.CharField(default='-', max_length=150)),
                ('Dateofhire', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('in_progress', 'อยู่ระหว่างการทำ'), ('completed', 'ทำเสร็จสิ้นแล้ว')], default='in_progress', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('Lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Phone', models.CharField(blank=True, max_length=10, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Birthday', models.DateField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('Hire_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Width', models.FloatField(verbose_name='Width (m.)')),
                ('Length', models.FloatField(verbose_name='Length (m.)')),
                ('Height', models.FloatField(verbose_name='Height (m.)')),
                ('Type', models.CharField(max_length=100)),
                ('Budget', models.FloatField()),
                ('Location', models.CharField(default='-', max_length=150)),
                ('Dateofhire', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('in_progress', 'อยู่ระหว่างการทำ'), ('completed', 'ทำเสร็จสิ้นแล้ว'), ('waiting_confirmation', 'รอการยืนยัน')], default='waiting_confirmation', max_length=20, verbose_name='Status')),
                ('QC_Number', models.IntegerField(unique=True)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hires', to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='PredictHire',
            fields=[
                ('Predict_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Width', models.FloatField()),
                ('Length', models.FloatField()),
                ('Height', models.FloatField()),
                ('Type', models.CharField(max_length=100)),
                ('Budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Area', models.FloatField(verbose_name='Area')),
                ('Wood', models.IntegerField(default=0, verbose_name='Wood (pc.)')),
                ('Paint', models.IntegerField(default=0, verbose_name='Paint (buck.)')),
                ('Lighting', models.IntegerField(default=0, verbose_name='Lighting (pc.)')),
                ('Nail', models.IntegerField(default=0, verbose_name='Nail (box.)')),
                ('Table', models.IntegerField(default=0, verbose_name='Table')),
                ('Chair', models.IntegerField(default=0, verbose_name='Chair')),
                ('Dateofhire', models.DateTimeField(default=django.utils.timezone.now)),
                ('HireA_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predict_hires', to='myapp.hireforadmin')),
                ('HireC_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predict_hires', to='myapp.hire')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('Resource_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Width', models.FloatField()),
                ('Length', models.FloatField()),
                ('Height', models.FloatField()),
                ('Type', models.CharField(max_length=100)),
                ('Location', models.CharField(blank=True, max_length=150, null=True)),
                ('Budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Wood_P', models.IntegerField(default=0, verbose_name='Wood (pc.) Predict')),
                ('Paint_P', models.IntegerField(default=0, verbose_name='Paint (buck.) Predict')),
                ('Lighting_P', models.IntegerField(default=0, verbose_name='Lighting (pc.) Predict')),
                ('Nail_P', models.IntegerField(default=0, verbose_name='Nail (box.) Predict')),
                ('Table_P', models.IntegerField(default=0, verbose_name='Table Predict')),
                ('Chair_P', models.IntegerField(default=0, verbose_name='Chair Predict')),
                ('Wood', models.IntegerField(default=0, verbose_name='Wood (pc.) Actual')),
                ('Paint', models.IntegerField(default=0, verbose_name='Paint (buck.)')),
                ('Lighting', models.IntegerField(default=0, verbose_name='Lighting (pc.) Actual')),
                ('Nail', models.IntegerField(default=0, verbose_name='Nail (box.) Actual')),
                ('Table', models.IntegerField(default=0, verbose_name='Table Actual')),
                ('Chair', models.IntegerField(default=0, verbose_name='Chair Actual')),
                ('Dateofhire', models.DateTimeField(blank=True, null=True)),
                ('DateSuccess', models.DateTimeField(default=django.utils.timezone.now)),
                ('Predict_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='myapp.predicthire')),
            ],
        ),
    ]
