# Generated by Django 5.1.3 on 2024-12-31 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('Hire_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Width', models.FloatField(verbose_name='Width (m.)')),
                ('Length', models.FloatField(verbose_name='Length (m.)')),
                ('Height', models.FloatField(verbose_name='Height (m.)')),
                ('Type', models.CharField(max_length=100)),
                ('Budget', models.CharField(max_length=150)),
                ('Location', models.CharField(max_length=150)),
                ('Finish_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
        ),
    ]
