# Generated by Django 5.1.3 on 2025-01-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_finish_date_hire_dateofhire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
