# Generated by Django 5.1.3 on 2025-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
