# Generated by Django 5.1.3 on 2025-01-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_member_address_alter_member_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='Status',
            field=models.CharField(choices=[('in_progress', 'อยู่ระหว่างการทำ'), ('completed', 'ทำเสร็จสิ้นแล้ว')], default='in_progress', max_length=20, verbose_name='สถานะ'),
        ),
    ]
